// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5kdzL8yMF17x6r4NYYRZq6vXs3iXIMaA',
    appId: '1:995910307024:web:9849dd2c5f6a2fb7c222d5',
    messagingSenderId: '995910307024',
    projectId: 'ugswms-9361c',
    authDomain: 'ugswms-9361c.firebaseapp.com',
    storageBucket: 'ugswms-9361c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxyAtIbAeHtAH2N1Cxat-fEzP9bvhbwM4',
    appId: '1:995910307024:android:b16ac4f2ff322e3cc222d5',
    messagingSenderId: '995910307024',
    projectId: 'ugswms-9361c',
    storageBucket: 'ugswms-9361c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPi3kG0LSKiGUnCT5h0rQqxxT628_1glk',
    appId: '1:995910307024:ios:ca035e4bac9d515ec222d5',
    messagingSenderId: '995910307024',
    projectId: 'ugswms-9361c',
    storageBucket: 'ugswms-9361c.firebasestorage.app',
    iosBundleId: 'com.example.ugswms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPi3kG0LSKiGUnCT5h0rQqxxT628_1glk',
    appId: '1:995910307024:ios:ca035e4bac9d515ec222d5',
    messagingSenderId: '995910307024',
    projectId: 'ugswms-9361c',
    storageBucket: 'ugswms-9361c.firebasestorage.app',
    iosBundleId: 'com.example.ugswms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5kdzL8yMF17x6r4NYYRZq6vXs3iXIMaA',
    appId: '1:995910307024:web:1fbbf1f27e01caa5c222d5',
    messagingSenderId: '995910307024',
    projectId: 'ugswms-9361c',
    authDomain: 'ugswms-9361c.firebaseapp.com',
    storageBucket: 'ugswms-9361c.firebasestorage.app',
  );
}
